In [2]:
import pandas as pd
from sklearn.svm import SVC
from sklearn.svm import LinearSVC
from sklearn import preprocessing
import numpy as np
import time
from sklearn.metrics import accuracy_score
from sklearn import cross_validation
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import confusion_matrix

In [3]:
def time_transform(x):
    if x >= 1000:
        x=0

In [32]:
database.groupby("g5").size()


g5
0     364
1      80
2      92
3     144
4      10
5     196
6      55
7      44
8     305
9      55
10     70
11     46
12     67
13    190
14     34
15     49
16     19
dtype: int64

In [33]:
database.describe()


dx    dy           g1    t1          vx1   vy1           g2  \
count  1820.000000  1820  1820.000000  1820  1820.000000  1820  1820.000000   
mean      2.343752     0     7.730220     0     0.186537     0     7.342308   
std       0.892665     0     4.035204     0     0.734500     0     4.317762   
min       0.000000     0     1.000000     0    -2.700677     0     0.000000   
25%       1.632121     0     5.000000     0    -0.021213     0     3.000000   
50%       1.980591     0     8.000000     0    -0.000209     0     8.000000   
75%       2.871147     0    11.000000     0     0.020388     0    11.000000   
max       4.502469     0    16.000000     0     4.413043     0    16.000000   

         t2          vx2   vy2  ...           vx3   vy3           g4    t4  \
count  1820  1820.000000  1820  ...   1820.000000  1820  1820.000000  1820   
mean      0     0.187368     0  ...      0.183327     0     6.571429     0   
std       0     0.731028     0  ...      0.724893     0     4.671726     0   
min       0    -2.700677     0  ...     -2.700677     0     0.000000     0   
25%       0    -0.018580     0  ...     -0.014960     0     2.000000     0   
50%       0    -0.000048     0  ...      0.000000     0     7.000000     0   
75%       0     0.017007     0  ...      0.013328     0    10.000000     0   
max       0     4.413043     0  ...      4.413043     0    16.000000     0   

               vx4   vy4           g5    t5          vx5   vy5  
count  1820.000000  1820  1820.000000  1820  1820.000000  1820  
mean      0.179910     0     6.200000     0     0.176263     0  
std       0.719756     0     4.795499     0     0.711420     0  
min      -2.700677     0     0.000000     0    -2.700677     0  
25%      -0.011314     0     2.000000     0    -0.010198     0  
50%       0.000000     0     6.000000     0     0.000000     0  
75%       0.010845     0    10.000000     0     0.007419     0  
max       4.413043     0    16.000000     0     4.413043     0  

[8 rows x 22 columns]

In [10]:
database = pd.read_csv("/home/jmirandadealme/Documents/SistAut/HumanRobotInteraction/others/TrainingData/todos.txt",
                      quotechar ="'")



#database["t5"] = 0
#database["t4"] = 0
#database["t3"] = 0
#database["t2"] = 0
#database["t1"] = 0




le = preprocessing.LabelEncoder()
le.fit(['0.0','closingforearm','armmovingdown','armmovingup',
        'armstopped','forearmstopped','handaboveelbow','handunderelbow',
        'openingforearm','walkingbackward','walkingforward','waving','nowalking',
        'calling', 'handing','elbowbehindbody','elbowinfrontofbody'])
database["g1"]=le.transform(database["g1"])
database["g2"]=le.transform(database["g2"])
database["g3"]=le.transform(database["g3"])
database["g4"]=le.transform(database["g4"])
database["g5"]=le.transform(database["g5"])

labels = database['label'].values

database.drop("label",axis=1,inplace=True)

database.head()

dx  dy  g1            t1       vx1  vy1  g2            t2       vx2  \
0  4.404114   0   1  1.448972e+09  4.404114    0   0  1.448972e+09  0.000000   
1  4.404114   0   5  1.448972e+09  4.404114    0   1  0.000000e+00  4.404114   
2  4.392251   0   3  1.448972e+09 -0.011864    0   5  1.000001e-01  4.404114   
3  4.392251   0   8  1.448972e+09 -0.011864    0   3  0.000000e+00 -0.011864   
4  4.364057   0  13  1.448972e+09 -0.028194    0   8  2.000000e-01 -0.011864   

   vy2 ...        vx3  vy3  g4            t4       vx4  vy4  g5            t5  \
0    0 ...   0.000000    0   0 -1.448972e+09  0.000000    0   0 -1.448972e+09   
1    0 ...   0.000000    0   0 -1.448972e+09  0.000000    0   0 -1.448972e+09   
2    0 ...   4.404114    0   0  1.448972e+09  0.000000    0   0 -1.448972e+09   
3    0 ...   4.404114    0   1 -1.000001e-01  4.404114    0   0  1.448972e+09   
4    0 ...  -0.011864    0   5 -9.999990e-02  4.404114    0   1 -3.000002e-01   

        vx5  vy5  
0  0.000000    0  
1  0.000000    0  
2  0.000000    0  
3  0.000000    0  
4  4.404114    0  

[5 rows x 22 columns]

In [18]:
database = pd.read_csv("/home/jmirandadealme/Documents/SistAut/HumanRobotInteraction/others/TrainingData/todos2.txt",
                      quotechar ="'")



labels = database['label'].values

database.drop("label",axis=1,inplace=True)

database.head()
features = database.values


dx  dy  g1  t1       vx1  vy1  g2   t2       vx2  vy2 ...        vx3  \
0  4.4041   0   6   0  4.404100    0   0  0.0  0.000000    0 ...   0.000000   
1  4.4041   0   1   0  4.404100    0   6  0.0  4.404100    0 ...   0.000000   
2  4.3923   0   5   0 -0.011864    0   1  0.1  4.404100    0 ...   4.404100   
3  4.3923   0   4   0 -0.011864    0   5  0.0 -0.011864    0 ...   4.404100   
4  4.3641   0   7   0 -0.028194    0   4  0.2 -0.011864    0 ...  -0.011864   

   vy3  g4   t4     vx4  vy4  g5   t5     vx5  vy5  
0    0   0  0.0  0.0000    0   0  0.0  0.0000    0  
1    0   0  0.0  0.0000    0   0  0.0  0.0000    0  
2    0   0  0.0  0.0000    0   0  0.0  0.0000    0  
3    0   6 -0.1  4.4041    0   0  0.0  0.0000    0  
4    0   1 -0.1  4.4041    0   6 -0.3  4.4041    0  

[5 rows x 22 columns]

In [9]:
features = database.values

pca = PCA(n_components =15)
pca.fit(features)
features = pca.transform(features)
print(pca.explained_variance_ratio_) 

[  3.37743890e-01   2.01711782e-01   1.68164746e-01   1.42381602e-01
   1.20348343e-01   9.29262207e-03   7.91749300e-03   4.39440280e-03
   4.11048516e-03   1.69402220e-03   9.13108798e-04   5.34345397e-04
   3.82116250e-04   3.32186986e-04   7.88547823e-05]


In [10]:
# TRAIN SVM


classf = SVC()
start_time = time.time()
classf.fit(features,labels)
print("--- %s seconds ---" % (time.time() - start_time))




--- 2.95648694038 seconds ---


In [42]:
# TRAIN LinearSVC


classf = LinearSVC()
start_time = time.time()
classf.fit(features,labels)
print("--- %s seconds ---" % (time.time() - start_time))



--- 0.801818847656 seconds ---


In [44]:
# TRAIN LogisticRegression

classf = LogisticRegression()
start_time = time.time()
classf.fit(features,labels)
print("--- %s seconds ---" % (time.time() - start_time))


--- 0.0455949306488 seconds ---


In [53]:
# TRAIN 3NN

classf = KNeighborsClassifier(n_neighbors=5)
start_time = time.time()
classf.fit(features,labels)
print("--- %s seconds ---" % (time.time() - start_time))


--- 0.00180292129517 seconds ---


In [48]:

# TRAIN AdaBoostClassifier

classf = AdaBoostClassifier()
start_time = time.time()
classf.fit(features,labels)
print("--- %s seconds ---" % (time.time() - start_time))


--- 0.232806921005 seconds ---


In [50]:
# Train SGDClassifier

classf = SGDClassifier()
start_time = time.time()
classf.fit(features,labels)
print("--- %s seconds ---" % (time.time() - start_time))


--- 0.00567102432251 seconds ---


In [11]:
# Predict

start_time = time.time()
predict_labels=classf.predict(features)
print("--- %s seconds ---" % (time.time() - start_time))
score = accuracy_score(labels,predict_labels)
print("Accuracy: %0.2f" % (score))
# Cross Validation
start_time = time.time()
scores = cross_validation.cross_val_score(classf, features, labels, cv=10)
print("--- %s seconds ---" % (time.time() - start_time))
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

--- 1.41111803055 seconds ---
Accuracy: 0.69
--- 23.1414158344 seconds ---
Accuracy: 0.39 (+/- 0.10)


In [12]:
# Predict 

start_time = time.time()
predict_labels=classf.predict(features)
print("--- %s seconds ---" % (time.time() - start_time))
score = accuracy_score(labels,predict_labels)
print("Accuracy: %0.2f" % (score))

cm = confusion_matrix(labels, predict_labels)
print('Confusion matrix, without normalization')
print(cm)
cm_normalized = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
print('Normalized confusion matrix')
print(cm_normalized)

--- 1.44975495338 seconds ---
Accuracy: 0.69
Confusion matrix, without normalization
[[833  46  17 181  20  44]
 [112 257   0 272   0   8]
 [ 18   0 365   8  99  45]
 [196  54   6 868  15  23]
 [ 27   0  50   2 577  62]
 [ 88   4  41  36  60 528]]
Normalized confusion matrix
[[ 0.73006135  0.04031551  0.01489921  0.15863278  0.01752848  0.03856266]
 [ 0.17257319  0.39599384  0.          0.41910632  0.          0.01232666]
 [ 0.03364486  0.          0.68224299  0.01495327  0.18504673  0.08411215]
 [ 0.1686747   0.0464716   0.00516351  0.74698795  0.01290878  0.01979346]
 [ 0.03760446  0.          0.06963788  0.00278552  0.80362117  0.08635097]
 [ 0.11624835  0.00528402  0.05416116  0.04755614  0.07926024  0.69749009]]


In [38]:
# Predict 

start_time = time.time()
predict_labels=classf.predict(features)
print("--- %s seconds ---" % (time.time() - start_time))
score = accuracy_score(labels,predict_labels)
print("Accuracy: %0.2f" % (score))

cm = confusion_matrix(labels, predict_labels)
print('Confusion matrix, without normalization')
print(cm)
cm_normalized = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
print('Normalized confusion matrix')
print(cm_normalized)

--- 0.486978054047 seconds ---
Accuracy: 0.76
Confusion matrix, without normalization
[[913  32   1  16  23   2   0]
 [ 24 269   5  21   0   6   2]
 [ 64  24 201  42   3   7   0]
 [ 14  14   7 325   0   6   0]
 [116   2   3   2 390   0   1]
 [ 28   8  10  22   0  52   1]
 [120  15   7  24  16   4  61]]
Normalized confusion matrix
[[ 0.92502533  0.03242148  0.00101317  0.01621074  0.02330294  0.00202634
   0.        ]
 [ 0.0733945   0.82262997  0.01529052  0.06422018  0.          0.01834862
   0.00611621]
 [ 0.18768328  0.07038123  0.58944282  0.12316716  0.00879765  0.02052786
   0.        ]
 [ 0.03825137  0.03825137  0.01912568  0.88797814  0.          0.01639344
   0.        ]
 [ 0.22568093  0.00389105  0.00583658  0.00389105  0.75875486  0.
   0.00194553]
 [ 0.23140496  0.0661157   0.08264463  0.18181818  0.          0.42975207
   0.00826446]
 [ 0.48582996  0.06072874  0.02834008  0.09716599  0.06477733  0.01619433
   0.24696356]]


In [8]:
database = pd.read_csv("/home/jmirandadealme/Documents/SistAut/HumanRobotInteraction/others/TrainingData/TUDO3.csv",
                      quotechar ="'")


labels = database['label'].values
database['label'].describe()

database.drop("label",axis=1,inplace=True)
features = database.values
database.describe()



dx    dy           g1    t1          vx1   vy1           g2  \
count  4962.000000  4962  4962.000000  4962  4962.000000  4962  4962.000000   
mean      2.964198     0     7.331520     0     0.009764     0     7.313785   
std       1.068869     0     4.935701     0     0.319837     0     4.941595   
min       1.077500     0     1.000000     0    -2.658700     0     0.000000   
25%       1.831800     0     4.000000     0    -0.028261     0     4.000000   
50%       3.510900     0     5.000000     0    -0.000713     0     5.000000   
75%       3.908425     0    12.000000     0     0.029559     0    12.000000   
max       4.496800     0    16.000000     0     4.286200     0    16.000000   

                t2          vx2   vy2  ...           vx3   vy3           g4  \
count  4962.000000  4962.000000  4962  ...   4962.000000  4962  4962.000000   
mean      0.201912     0.009872     0  ...      0.010018     0     7.286175   
std       0.475432     0.319805     0  ...      0.319766     0     4.951399   
min       0.000000    -2.658700     0  ...     -2.658700     0     0.000000   
25%       0.001000    -0.028200     0  ...     -0.027810     0     4.000000   
50%       0.100000    -0.000665     0  ...     -0.000645     0     5.000000   
75%       0.201000     0.029559     0  ...      0.029559     0    12.000000   
max      15.200000     4.286200     0  ...      4.286200     0    16.000000   

                t4          vx4   vy4           g5           t5          vx5  \
count  4962.000000  4962.000000  4962  4962.000000  4962.000000  4962.000000   
mean     -0.199197     0.009935     0     7.266223    -0.398190     0.009882   
std       0.803734     0.319698     0     4.955747     0.917902     0.319657   
min     -15.502000    -2.658700     0     0.000000   -15.502000    -2.658700   
25%      -0.300750    -0.027502     0     4.000000    -0.503000    -0.027440   
50%      -0.102000    -0.000628     0     5.000000    -0.208000    -0.000599   
75%       0.001000     0.029271     0    12.000000    -0.098000     0.029080   
max      14.903000     4.286200     0    16.000000    13.900000     4.286200   

        vy5  
count  4962  
mean      0  
std       0  
min       0  
25%       0  
50%       0  
75%       0  
max       0  

[8 rows x 22 columns]