In [1]:
import pandas as pd
from sklearn.svm import SVC
from sklearn.svm import LinearSVC
from sklearn import preprocessing
import numpy as np
import time
from sklearn.metrics import accuracy_score
from sklearn import cross_validation
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import confusion_matrix

In [3]:
def time_transform(x):
    if x >= 1000:
        x=0

In [32]:
database.groupby("g5").size()


g5
0     364
1      80
2      92
3     144
4      10
5     196
6      55
7      44
8     305
9      55
10     70
11     46
12     67
13    190
14     34
15     49
16     19
dtype: int64

In [33]:
database.describe()


dx    dy           g1    t1          vx1   vy1           g2  \
count  1820.000000  1820  1820.000000  1820  1820.000000  1820  1820.000000   
mean      2.343752     0     7.730220     0     0.186537     0     7.342308   
std       0.892665     0     4.035204     0     0.734500     0     4.317762   
min       0.000000     0     1.000000     0    -2.700677     0     0.000000   
25%       1.632121     0     5.000000     0    -0.021213     0     3.000000   
50%       1.980591     0     8.000000     0    -0.000209     0     8.000000   
75%       2.871147     0    11.000000     0     0.020388     0    11.000000   
max       4.502469     0    16.000000     0     4.413043     0    16.000000   

         t2          vx2   vy2  ...           vx3   vy3           g4    t4  \
count  1820  1820.000000  1820  ...   1820.000000  1820  1820.000000  1820   
mean      0     0.187368     0  ...      0.183327     0     6.571429     0   
std       0     0.731028     0  ...      0.724893     0     4.671726     0   
min       0    -2.700677     0  ...     -2.700677     0     0.000000     0   
25%       0    -0.018580     0  ...     -0.014960     0     2.000000     0   
50%       0    -0.000048     0  ...      0.000000     0     7.000000     0   
75%       0     0.017007     0  ...      0.013328     0    10.000000     0   
max       0     4.413043     0  ...      4.413043     0    16.000000     0   

               vx4   vy4           g5    t5          vx5   vy5  
count  1820.000000  1820  1820.000000  1820  1820.000000  1820  
mean      0.179910     0     6.200000     0     0.176263     0  
std       0.719756     0     4.795499     0     0.711420     0  
min      -2.700677     0     0.000000     0    -2.700677     0  
25%      -0.011314     0     2.000000     0    -0.010198     0  
50%       0.000000     0     6.000000     0     0.000000     0  
75%       0.010845     0    10.000000     0     0.007419     0  
max       4.413043     0    16.000000     0     4.413043     0  

[8 rows x 22 columns]

In [10]:
database = pd.read_csv("/home/jmirandadealme/Documents/SistAut/HumanRobotInteraction/others/TrainingData/todos.txt",
                      quotechar ="'")



#database["t5"] = 0
#database["t4"] = 0
#database["t3"] = 0
#database["t2"] = 0
#database["t1"] = 0




le = preprocessing.LabelEncoder()
le.fit(['0.0','closingforearm','armmovingdown','armmovingup',
        'armstopped','forearmstopped','handaboveelbow','handunderelbow',
        'openingforearm','walkingbackward','walkingforward','waving','nowalking',
        'calling', 'handing','elbowbehindbody','elbowinfrontofbody'])
database["g1"]=le.transform(database["g1"])
database["g2"]=le.transform(database["g2"])
database["g3"]=le.transform(database["g3"])
database["g4"]=le.transform(database["g4"])
database["g5"]=le.transform(database["g5"])

labels = database['label'].values

database.drop("label",axis=1,inplace=True)

database.head()

dx  dy  g1            t1       vx1  vy1  g2            t2       vx2  \
0  4.404114   0   1  1.448972e+09  4.404114    0   0  1.448972e+09  0.000000   
1  4.404114   0   5  1.448972e+09  4.404114    0   1  0.000000e+00  4.404114   
2  4.392251   0   3  1.448972e+09 -0.011864    0   5  1.000001e-01  4.404114   
3  4.392251   0   8  1.448972e+09 -0.011864    0   3  0.000000e+00 -0.011864   
4  4.364057   0  13  1.448972e+09 -0.028194    0   8  2.000000e-01 -0.011864   

   vy2 ...        vx3  vy3  g4            t4       vx4  vy4  g5            t5  \
0    0 ...   0.000000    0   0 -1.448972e+09  0.000000    0   0 -1.448972e+09   
1    0 ...   0.000000    0   0 -1.448972e+09  0.000000    0   0 -1.448972e+09   
2    0 ...   4.404114    0   0  1.448972e+09  0.000000    0   0 -1.448972e+09   
3    0 ...   4.404114    0   1 -1.000001e-01  4.404114    0   0  1.448972e+09   
4    0 ...  -0.011864    0   5 -9.999990e-02  4.404114    0   1 -3.000002e-01   

        vx5  vy5  
0  0.000000    0  
1  0.000000    0  
2  0.000000    0  
3  0.000000    0  
4  4.404114    0  

[5 rows x 22 columns]

In [18]:
database = pd.read_csv("/home/jmirandadealme/Documents/SistAut/HumanRobotInteraction/others/TrainingData/todos2.txt",
                      quotechar ="'")



labels = database['label'].values

database.drop("label",axis=1,inplace=True)

database.head()
features = database.values


dx  dy  g1  t1       vx1  vy1  g2   t2       vx2  vy2 ...        vx3  \
0  4.4041   0   6   0  4.404100    0   0  0.0  0.000000    0 ...   0.000000   
1  4.4041   0   1   0  4.404100    0   6  0.0  4.404100    0 ...   0.000000   
2  4.3923   0   5   0 -0.011864    0   1  0.1  4.404100    0 ...   4.404100   
3  4.3923   0   4   0 -0.011864    0   5  0.0 -0.011864    0 ...   4.404100   
4  4.3641   0   7   0 -0.028194    0   4  0.2 -0.011864    0 ...  -0.011864   

   vy3  g4   t4     vx4  vy4  g5   t5     vx5  vy5  
0    0   0  0.0  0.0000    0   0  0.0  0.0000    0  
1    0   0  0.0  0.0000    0   0  0.0  0.0000    0  
2    0   0  0.0  0.0000    0   0  0.0  0.0000    0  
3    0   6 -0.1  4.4041    0   0  0.0  0.0000    0  
4    0   1 -0.1  4.4041    0   6 -0.3  4.4041    0  

[5 rows x 22 columns]

In [4]:
features = database.values

pca = PCA(n_components =15)
pca.fit(features)
features = pca.transform(features)
print(pca.explained_variance_ratio_) 

[  3.41075561e-01   2.04474748e-01   1.65213234e-01   1.37854263e-01
   1.19375843e-01   9.99085085e-03   8.09580060e-03   5.43457207e-03
   5.07140803e-03   1.55046669e-03   7.66478711e-04   4.26981025e-04
   3.16093286e-04   2.74146560e-04   7.95531898e-05]


In [5]:
# TRAIN SVM


classf = SVC()
start_time = time.time()
classf.fit(features,labels)
print("--- %s seconds ---" % (time.time() - start_time))




--- 1.27509903908 seconds ---


In [42]:
# TRAIN LinearSVC


classf = LinearSVC()
start_time = time.time()
classf.fit(features,labels)
print("--- %s seconds ---" % (time.time() - start_time))



--- 0.801818847656 seconds ---


In [44]:
# TRAIN LogisticRegression

classf = LogisticRegression()
start_time = time.time()
classf.fit(features,labels)
print("--- %s seconds ---" % (time.time() - start_time))


--- 0.0455949306488 seconds ---


In [53]:
# TRAIN 3NN

classf = KNeighborsClassifier(n_neighbors=5)
start_time = time.time()
classf.fit(features,labels)
print("--- %s seconds ---" % (time.time() - start_time))


--- 0.00180292129517 seconds ---


In [48]:

# TRAIN AdaBoostClassifier

classf = AdaBoostClassifier()
start_time = time.time()
classf.fit(features,labels)
print("--- %s seconds ---" % (time.time() - start_time))


--- 0.232806921005 seconds ---


In [50]:
# Train SGDClassifier

classf = SGDClassifier()
start_time = time.time()
classf.fit(features,labels)
print("--- %s seconds ---" % (time.time() - start_time))


--- 0.00567102432251 seconds ---


In [6]:
# Predict

start_time = time.time()
predict_labels=classf.predict(features)
print("--- %s seconds ---" % (time.time() - start_time))
score = accuracy_score(labels,predict_labels)
print("Accuracy: %0.2f" % (score))
# Cross Validation
start_time = time.time()
scores = cross_validation.cross_val_score(classf, features, labels, cv=10)
print("--- %s seconds ---" % (time.time() - start_time))
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

--- 0.623461008072 seconds ---
Accuracy: 0.73
--- 10.7973909378 seconds ---
Accuracy: 0.43 (+/- 0.03)


In [7]:
# Predict 

start_time = time.time()
predict_labels=classf.predict(features)
print("--- %s seconds ---" % (time.time() - start_time))
score = accuracy_score(labels,predict_labels)
print("Accuracy: %0.2f" % (score))

cm = confusion_matrix(labels, predict_labels)
print('Confusion matrix, without normalization')
print(cm)
cm_normalized = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
print('Normalized confusion matrix')
print(cm_normalized)

--- 0.620098829269 seconds ---
Accuracy: 0.73
Confusion matrix, without normalization
[[719  94  20  11   6  34]
 [ 92 408   1  12   0   9]
 [ 26   0 386   1   8  33]
 [148  77  16 218   1  38]
 [ 29   0  60   1 222  44]
 [ 73  18  36   6  11 436]]
Normalized confusion matrix
[[ 0.81334842  0.10633484  0.02262443  0.01244344  0.00678733  0.03846154]
 [ 0.17624521  0.7816092   0.00191571  0.02298851  0.          0.01724138]
 [ 0.05726872  0.          0.85022026  0.00220264  0.01762115  0.07268722]
 [ 0.29718876  0.15461847  0.03212851  0.437751    0.00200803  0.07630522]
 [ 0.08146067  0.          0.16853933  0.00280899  0.62359551  0.12359551]
 [ 0.12586207  0.03103448  0.06206897  0.01034483  0.01896552  0.75172414]]


In [38]:
# Predict 

start_time = time.time()
predict_labels=classf.predict(features)
print("--- %s seconds ---" % (time.time() - start_time))
score = accuracy_score(labels,predict_labels)
print("Accuracy: %0.2f" % (score))

cm = confusion_matrix(labels, predict_labels)
print('Confusion matrix, without normalization')
print(cm)
cm_normalized = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
print('Normalized confusion matrix')
print(cm_normalized)

--- 0.486978054047 seconds ---
Accuracy: 0.76
Confusion matrix, without normalization
[[913  32   1  16  23   2   0]
 [ 24 269   5  21   0   6   2]
 [ 64  24 201  42   3   7   0]
 [ 14  14   7 325   0   6   0]
 [116   2   3   2 390   0   1]
 [ 28   8  10  22   0  52   1]
 [120  15   7  24  16   4  61]]
Normalized confusion matrix
[[ 0.92502533  0.03242148  0.00101317  0.01621074  0.02330294  0.00202634
   0.        ]
 [ 0.0733945   0.82262997  0.01529052  0.06422018  0.          0.01834862
   0.00611621]
 [ 0.18768328  0.07038123  0.58944282  0.12316716  0.00879765  0.02052786
   0.        ]
 [ 0.03825137  0.03825137  0.01912568  0.88797814  0.          0.01639344
   0.        ]
 [ 0.22568093  0.00389105  0.00583658  0.00389105  0.75875486  0.
   0.00194553]
 [ 0.23140496  0.0661157   0.08264463  0.18181818  0.          0.42975207
   0.00826446]
 [ 0.48582996  0.06072874  0.02834008  0.09716599  0.06477733  0.01619433
   0.24696356]]


In [3]:
database = pd.read_csv("/home/jmirandadealme/Documents/SistAut/HumanRobotInteraction/others/TrainingData/TUDO2.csv",
                      quotechar ="'")



labels = database['label'].values

database.drop("label",axis=1,inplace=True)
features = database.values
database.describe()



dx    dy           g1    t1          vx1   vy1           g2  \
count  3294.000000  3294  3294.000000  3294  3294.000000  3294  3294.000000   
mean      2.902355     0     7.637523     0     0.004513     0     7.622040   
std       1.041121     0     5.048120     0     0.306150     0     5.050803   
min       1.077500     0     1.000000     0    -2.658700     0     0.000000   
25%       1.827225     0     4.000000     0    -0.042105     0     4.000000   
50%       3.203650     0     5.000000     0    -0.001262     0     5.000000   
75%       3.881600     0    12.000000     0     0.050741     0    12.000000   
max       4.409300     0    16.000000     0     4.159800     0    16.000000   

                t2          vx2   vy2  ...           vx3   vy3           g4  \
count  3294.000000  3294.000000  3294  ...   3294.000000  3294  3294.000000   
mean      0.210529     0.004613     0  ...      0.004754     0     7.598664   
std       0.536758     0.306114     0  ...      0.306072     0     5.057922   
min       0.000000    -2.658700     0  ...     -2.658700     0     0.000000   
25%       0.001000    -0.041935     0  ...     -0.040592     0     4.000000   
50%       0.099500    -0.001226     0  ...     -0.001215     0     5.000000   
75%       0.200000     0.050741     0  ...      0.050741     0    12.000000   
max      15.200000     4.159800     0  ...      4.159800     0    16.000000   

                t4          vx4   vy4           g5           t5          vx5  \
count  3294.000000  3294.000000  3294  3294.000000  3294.000000  3294.000000   
mean     -0.208984     0.004628     0     7.587735    -0.417731     0.004607   
std       0.911088     0.305964     0     5.059985     1.037156     0.305924   
min     -15.502000    -2.658700     0     0.000000   -15.502000    -2.658700   
25%      -0.301000    -0.040561     0     4.000000    -0.510000    -0.040561   
50%      -0.101000    -0.001193     0     5.000000    -0.205000    -0.001154   
75%       0.001000     0.050612     0    12.000000    -0.097000     0.050612   
max      14.903000     4.159800     0    16.000000    13.900000     4.159800   

        vy5  
count  3294  
mean      0  
std       0  
min       0  
25%       0  
50%       0  
75%       0  
max       0  

[8 rows x 22 columns]